apiVersion: apps/v1
kind: Deployment
metadata:
  name:  devop-app
  namespace: default
  labels:
    app:  devop-app
spec:
  selector:
    matchLabels:
      app: devop-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  devop-app
      
    spec:
      containers:
      - name:  devop-app
        image:  #{CONTAINER_REGISTRY}#/#{image_name}#:#{Build.BuildId}#
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8501 
          name:  devop-app
      restartPolicy: Always
--- 
kind: Service
apiVersion: v1
metadata:
  name: devops-service
spec:
  selector:
    app:  devop-app
  type:  LoadBalancer 
  ports:
  - name: devops-service
    port:  8501
    targetPort:  8501     

---

